# Generated by Django 3.1.2 on 2020-10-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoapp', '0003_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(unique=True, upload_to='pizzaimages/'),
        ),
    ]
