# Generated by Django 3.1.2 on 2020-10-13 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoapp', '0004_auto_20201012_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=500)),
                ('cust_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zomatoapp.customer')),
            ],
        ),
    ]
