# Generated by Django 3.1.2 on 2020-10-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoapp', '0008_auto_20201014_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
